sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CQW+7enwGyFq+y3JYWB5bwFzuoUgwIOzyOYjc4p4NP9BmHkM8joskHeLwoFN1GhL9smGCnXMJCxtsnI4Hhbz3/29pNjYflKBsASZsBSYGmTfH2fevTa61cCeqXznLgsDxj5lZaE4GzK3yzblnSL5ZD8AATqOCxCO0/1BsylcWr6ORYK3NGdKwQjuL0cUckwG5f4o2eDe+0KeXOD71d/cmAJ5FOV7AVqAPwdfV7HuxDy9t+k2skQTvXhMiqLFJ7UgHOQTtt1pjg/h3cA85TCOZDwUy843zusY9jVVBz/ne86H+YY0Tn/0pek6TRKbWCjFx24kg1tBFieFCrmBiVvy+HupOj72AtSJSvETe+p2MFaVUZtxd/beObq3s9Z3zw6CYJYQCUpz0RQEFHYmWU2N94LDTwgG6PR4xtKleDTcGyouLA8Mo8Writ8Tw8l/PREYbHOuTw9UL9ZiZ2HPkT6ZF3+l72pP0zNXk7dzGJt9ZnBNYHeytALqB26kI3qspV5V/9xqMoca7+QOFfte8UcE9/OL7K/xD4a/NEsjAScMKkxKTZ1mbRrS4vTL9c12MWnQuIhfneF4ZLdhi2KxQIoSvhk7W8cpmtDQfRT0xCajpcxb58BIB47ZVZOiBQk96AAsme1LoZ0TJZsmyW6WiTjt54yMb2v8dsgAs7seJlHDDu4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Peck-s-Bad-Boy-with-the-Cowboys_6141
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy